export { default as Header } from './header'
export { default as HowIs } from './howIs'
export { default as SectionPhoto } from './sectionPhoto'
export { default as SectionSlider } from './sectionSlider'
export { default as SectionSlider2 } from './sectionSlider'
